spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://lollipop.yorhp.com:3306/fileManager
    username: dhht
    password: Dhht2018
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

