spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://lollipop.yorhp.com:3306/fileManager
    username: dhht
    password: Dhht2018
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
      multipart:
        max-file-size: 1000MB
        max-request-size: 1000MB
